### ISSUE TITLE
Can't create Cosmos Kernel

### ISSUE THREAD

**Issue by vapmawtf** [PratyushKing/cosmosCLI#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Can't create Cosmos Kernel
**Screenshots**
![image](https://github.com/PratyushKing/cosmosCLI/assets/100956266/8c4d1ccd-f8ea-4e6b-aca6-c53bdac733a3)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
There's no cosmosCSKernel template on nuget
![image](https://github.com/PratyushKing/cosmosCLI/assets/100956266/13d0bf6c-f1e9-4220-bfbe-127c97bc97cf)

**Comment by glintpry** [comment]
Oh you need to install the cosmos templates, just manually install cosmos with its install page and use that, the reinstall cosmos thing is broken rn

**Comment by vapmawtf** [comment]
Okay, thanks

**Comment by vapmawtf** [comment]
Btw can I add cosmos cli to my package manager?

**Comment by glintpry** [comment]
> Btw can I add cosmos cli to my package manager?

yeah sure that would be great help! whats it called

**Comment by vapmawtf** [comment]
GitMan

**Comment by glintpry** [comment]
> GitMan

sure 👍🏻

**Comment by glintpry** [comment]
also I do appreciate you using the `-c` and `-r` rather than the noob-friendly versions `--create` and `--run`

**Comment by vapmawtf** [comment]
> also I do appreciate you using the `-c` and `-r` rather than the noob-friendly versions `--create` and `--run`

Imagine using aptidute instead of apt

**Comment by glintpry** [comment]
> Imagine using aptidute instead of apt

Imagine using pacaur instead of yay 💀

**Comment by vapmawtf** [comment]
> > Imagine using aptidute instead of apt
> 
> Imagine using pacaur instead of yay 💀 

Imagine using --help instead of -h 💀💀💀
